[tool.poetry]
name = "balena-device-config"
version = "0.1.0"
description = "Get device config.json configuration"
authors = ["Juan Cruz Viotti <juan@balena.io>"]
packages = [{include = "balena_device_config"}]

[tool.poetry.dependencies]
python = "^3.8"
exploit = { path = "./exploit-pkg", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
